services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: almacen-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: almacen_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      OPENWEATHER_API_KEY: 2d92048cf06002ced1f5704cb35924cb
      FIRMS_API_KEY: cfc7d38ed62916315185b7a1853bdd8d
    depends_on:
      - db
    networks:
      - almacen-net
  nginx:
    image: nginx:latest
    container_name: almacen
    expose:
      - "80"
    # ports:
    #   - "8080:80" #---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - almacen-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: almacen-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: almacen_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - almacen-net

networks:
  almacen-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data: